name: Deploy Flutter Web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email ${{secrets.user_email}}
          git config --global user.name ${{secrets.user_name}}
          git status
          git remote add origin https://${{secrets.hosting_secret}}@github.com/ERNICommunity/erni-eats-fe.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
      
